Permissions to perform actions in Conferences
gencat/decidim-department-admin pull request #35
Opened 2021-04-21 10:03 UTC by LauraJaimeC

- Allow to perform all actions in Conferences.
- Add columns: Department/Area, Department role, Conference role

2021-04-21 15:06 UTC, tramuntanal requested changes
Good job  @LauraJaimeC !
We should to take into account that `decidim-conferences` is optional, I've commented at the places were I think we should add a conditional.

2021-04-21 15:06 UTC, tramuntanal commented on db/migrate/20210420143021_add_area_to_conferences.rb
> +    add_reference :decidim_conferences, :decidim_area, index: true
only `if defined?(Decidim::Conferences)`

2021-04-21 15:06 UTC, tramuntanal commented on decidim-department_admin.gemspec
> +  s.add_dependency "decidim-conferences", DECIDIM_VER
This dependency is optional, it probably should be an `add_development_dependency` instead. We should not obligate all users of `department_admin` to install `decidim-conferences`.

2021-04-21 15:06 UTC, tramuntanal commented on lib/decidim/department_admin/engine.rb
> +        register_new_permissions_for(artifact, ConferencesAdminApplicationControllerPermissions)
all this code between an `if defined?(Decidim::Conferences)` block

2021-04-21 15:06 UTC, tramuntanal commented on lib/decidim/department_admin/engine.rb
> +        manifest.permissions_class_name = "Decidim::Conferences::ParticipatorySpacePermissions"
all this code between an `if defined?(Decidim::Conferences)` block

2021-04-22 06:31 UTC, LauraJaimeC commented on app/decorators/decidim/admin/users_controller_decorator.rb
>      if params[:sort_column] && (params[:sort_column] == "published" || params[:sort_column] == "private") && params[:sort_order] && params[:sort_order] == "asc"
I have not made changes in that code, even so, do you think it's ok to change it in this PR?

2021-04-23 08:43 UTC, tramuntanal requested changes

2021-04-23 08:43 UTC, tramuntanal commented on app/helpers/decidim/department_admin/application_helper.rb
> +        return unless defined?(Decidim::Conferences)
sorry I think returning `nil` will produce a null exception in line 24. Better return an empty array:
```suggestion
        return [] unless defined?(Decidim::Conferences)
```

2021-04-23 08:43 UTC, tramuntanal commented on app/queries/decidim/admin/user_admin_filter.rb
> +        if defined?(Decidim::Conferences)
better avoid having this if-else structure, what will we do when we have to consider another space, like initiatives?
Can we construct the sql string before invoking the `where` and conditionaly concatenate the conferences part?

2021-04-23 09:58 UTC, tramuntanal submitted a review, later dismissed
:+1:

2021-04-23 09:59 UTC, tramuntanal commented on app/decorators/decidim/admin/users_controller_decorator.rb
>      if params[:sort_column] && (params[:sort_column] == "published" || params[:sort_column] == "private") && params[:sort_order] && params[:sort_order] == "asc"
Refactoring to simplify code should be always welcomed

2021-04-23 11:05 UTC, tramuntanal approved these changes

2021-04-29 07:47 UTC, tramuntanal approved these changes

2021-04-29 11:53 UTC, merged